#include "Configurator.h"
#include "Mapping.h"

#include <Context.h>
#include <Configuration.h>
#include <MappedFile.h>

#include <string>

using namespace System::IO;
using namespace parity::utils;

namespace paritygraphicalconfigurator {
	System::Void Configurator::EditItemDetails(System::Object^  sender, System::EventArgs^  e)
	{
		MappingStruct* ptr = SettingMapping;
		ListViewItem^ lvi = lvSettings->SelectedItems[0];

		if(lvi)
		{
			while(ptr->Name)
			{
				if(lvi->SubItems[0]->Text == gcnew String(ptr->Name))
				{
					ptr->Edit(ptr, *context_);
					break;
				}

				++ptr;
			}
		}

		CreateConfigurationView(*context_);
	}

	System::Void Configurator::NewConfiguration(System::Object^  sender, System::EventArgs^  e)
	{
		InitNewContext();
		CreateConfigurationView(*context_);
	}

	bool Configurator::InitNewContext()
	{
		if(context_ && initial_ && *context_ != *initial_)
		{
			if(MessageBox::Show("Discard changes to current configuration?", "Discard changes?", MessageBoxButtons::OKCancel, MessageBoxIcon::Question) == System::Windows::Forms::DialogResult::Cancel)
				return false;
		}

		context_ = new Context();
		initial_ = new Context();

		return true;
	}

	System::Void Configurator::OpenConfiguration(System::Object^  sender, System::EventArgs^  e)
	{
		if(dlgOpenFile->ShowDialog() == System::Windows::Forms::DialogResult::OK)
		{
			if(!InitNewContext())
				return;
			
			std::string native = MarshalSimpleStringToNative(dlgOpenFile->FileName);
			MappedFile file(parity::utils::Path(native), ModeRead);

			Config::parseFile(*context_, file);
			*initial_ = *context_;

			CreateConfigurationView(*context_);
		}
	}

	System::Void Configurator::SaveConfiguration(System::Object^  sender, System::EventArgs^  e)
	{
		if(dlgSaveFile->ShowDialog() == System::Windows::Forms::DialogResult::OK)
		{
			MappingStruct* ptr = SettingMapping;
			StreamWriter^ writer = gcnew StreamWriter(dlgSaveFile->FileName, false, System::Text::Encoding::ASCII);

			writer->Write("#\n# Configuration File for parity generated by parity.graphical.configurator.\n");
			writer->Write("# Both parity and parity.graphical.configurator are Copyright (c) 2007, 2008\n");
			writer->Write("# by Markus Duft (markus.duft at salomon dot at).\n#\n");
			
			writer->Write("# WARNING: The parity.graphical.configurator only writes settings to the\n");
			writer->Write("# Configuration File if they differ from the default value!\n#\n\n");

			while(ptr->Name)
			{
				if(!ptr->IsDefault(*context_))
				{
					writer->Write("# Name: {0}, Default Value: {1}, Type {2}\n", 
						gcnew String(ptr->Name), gcnew String(ptr->Default), gcnew String(ptr->Type));

					ptr->Save(writer, ptr, *context_);
				}

				++ptr;
			}

			writer->Flush();
			writer->Close();
		}
	}

	System::Void Configurator::CreateConfigurationView(parity::utils::Context& ctx)
	{
		MappingStruct * ptr = SettingMapping;

		lvSettings->Items->Clear();

		while(ptr->Name && ptr->Formatter)
		{
			ListViewItem^ lvi = 
				gcnew ListViewItem(
					gcnew array<String^>
						{
							gcnew String(ptr->Name), 
							gcnew String(ptr->Type), 
							ptr->Formatter(ctx), 
							gcnew String(ptr->Default)
						}
					, 0
				);

			if(ptr->IsDefault(ctx))
			{
				lvi->Group = lvSettings->Groups[1];
			} else {
				lvi->Group = lvSettings->Groups[0];
			}

			lvSettings->Items->Add(lvi);

			++ptr;
		}
	}

	//
	// Helper functions
	//

	std::string Configurator::MarshalSimpleStringToNative(String^ str)
	{
		IntPtr native = System::Runtime::InteropServices::Marshal::StringToHGlobalAnsi(str);
		std::string result((char*)native.ToPointer());
		System::Runtime::InteropServices::Marshal::FreeHGlobal(native);

		return result;
	}

	String^ Configurator::MarshalSimpleNativeToString(std::string& str)
	{
		return gcnew String(str.c_str());
	}
}
